version: '3.9'

services:
    postgres:
        image: postgres:17
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

    mongo:
        image: mongo:6
        container_name: mongo
        restart: always
        ports:
            - '${MONGO_PORT}:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DB}
        volumes:
            - mongo_data:/data/db

    redis:
        image: redis:7
        container_name: redis
        restart: always
        ports:
            - '${REDIS_PORT}:6379'
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        volumes:
            - redis_data:/data

volumes:
    postgres_data:
    mongo_data:
    redis_data:
