export enum TaxIdIso2Enum {
	// === Américas ===
	AR = 'AR', // Argentina (CUIT)
	BO = 'BO', // Bolívia (NIT)
	BR = 'BR', // Brasil (CPF / CNPJ)
	CA = 'CA', // Canadá (SIN)
	CL = 'CL', // Chile (RUT)
	CO = 'CO', // Colômbia (NIT)
	CR = 'CR', // Costa Rica (Cédula)
	DO = 'DO', // Rep. Dominicana (RNC)
	EC = 'EC', // Equador (RUC)
	GT = 'GT', // Guatemala (NIT)
	HN = 'HN', // Honduras (RTN)
	MX = 'MX', // México (RFC)
	NI = 'NI', // Nicarágua (RUC)
	PA = 'PA', // Panamá (RUC)
	PE = 'PE', // Peru (RUC)
	PY = 'PY', // Paraguai (RUC)
	SV = 'SV', // El Salvador (NIT)
	US = 'US', // Estados Unidos (SSN / EIN)
	UY = 'UY', // Uruguai (RUT)
	VE = 'VE', // Venezuela (RIF)

	// == ===
	AD = 'AD', // Andorra (NRT)
	AT = 'AT', // Áustria (UID)
	BE = 'BE', // Bélgica (NISS) - (também nl-BE)
	BG = 'BG', // Bulgária (EGN / Bulstat)
	BY = 'BY', // Belarus (UNP)
	CH = 'CH', // Suíça (IDE) - (também de-CH, it-CH)
	CY = 'CY', // Chipre (TIN)
	CZ = 'CZ', // Rep. Tcheca (Rodné číslo)
	DE = 'DE', // Alemanha (Steuer-IdNr)
	DK = 'DK', // Dinamarca (CPR / CVR)
	EE = 'EE', // Estônia (Isikukood)
	ES = 'ES', // Espanha (DNI / NIE / NIF)
	FI = 'FI', // Finlândia (HETU / Y-tunnus)
	FO = 'FO', // Ilhas Faroe (P-tal)
	FR = 'FR', // França (SPI - numéro fiscal)
	GB = 'GB', // Reino Unido (UTR / NINO)
	GE = 'GE', // Geórgia (TIN)
	GR = 'GR', // Grécia (AFM)
	HR = 'HR', // Croácia (OIB)
	HU = 'HU', // Hungria (Adóazonosító jel)
	IE = 'IE', // Irlanda (PPSN / TRN)
	IS = 'IS', // Islândia (Kennitala)
	IT = 'IT', // Itália (Codice Fiscale)
	LI = 'LI', // Liechtenstein (PEID)
	LT = 'LT', // Lituânia (Asmens kodas)
	LU = 'LU', // Luxemburgo (ID number)
	LV = 'LV', // Letônia (Personas kods)
	MC = 'MC', // Mônaco (TVA)
	MT = 'MT', // Malta (TIN)
	NL = 'NL', // Holanda (BSN)
	NO = 'NO', // Noruega (Fødselsnummer)
	PL = 'PL', // Polônia (PESEL / NIP)
	PT = 'PT', // Portugal (NIF)
	RO = 'RO', // Romênia (CNP / CUI)
	RU = 'RU', // Rússia (INN)
	SE = 'SE', // Suécia (Personnummer)
	SI = 'SI', // Eslovênia (Davčna številka)
	SK = 'SK', // Eslováquia (Rodné číslo)
	TR = 'TR', // Turquia (TC Kimlik No)
	UA = 'UA', // Ucrânia (RNTRC)

	// == Oceania ===
	AU = 'AU', // Austrália (TFN)
	BD = 'BD', // Bangladesh (TIN)
	CN = 'CN', // China (Unified Social Credit Code)
	HK = 'HK', // Hong Kong (HKID)
	ID = 'ID', // Indonésia (NPWP)
	IN = 'IN', // Índia (PAN)
	IR = 'IR', // Irã (National ID) - (Aqui está o Irã!)
	JP = 'JP', // Japão (My Number)
	KR = 'KR', // Coreia do Sul (RRN)
	KZ = 'KZ', // Cazaquistão (IIN / BIN)
	MY = 'MY', // Malásia (NRIC)
	NZ = 'NZ', // Nova Zelândia (IRD Number)
	PH = 'PH', // Filipinas (TIN)
	SG = 'SG', // Singapura (NRIC / FIN)
	TH = 'TH', // Tailândia (Tax ID)
	TW = 'TW', // Taiwan (Tax ID)
	UZ = 'UZ', // Uzbequistão (TIN)
	VN = 'VN', // Vietnã (MST)

	// ==e Médio / África ===
	AE = 'AE', // Emirados Árabes Unidos (TIN)
	BH = 'BH', // Bahrein (CPR / TIN)
	EG = 'EG', // Egito (NID)
	IL = 'IL', // Israel (ID Number)
	JO = 'JO', // Jordânia (TIN)
	NG = 'NG', // Nigéria (TIN)
	SA = 'SA', // Arábia Saudita (TIN)
	SY = 'SY', // Síria (NIN)
	ZA = 'ZA', // África do Sul (Tax ID)
}
