import type { MigrationFn } from 'umzug'
import type { PrismaClient } from '@prisma/client'

export const up: MigrationFn<{ prisma: PrismaClient }> = async ({
	context,
}) => {
	console.log('🔄 Executando migration de países...')
	const { prisma } = context

	await prisma.country.createMany({
		data: [
			{
				name: 'Afghanistan',
				iso2: 'AF',
				iso3: 'AFG',
				locale: 'fa-AF',
				phoneCode: '+93',
			},
			{
				name: 'Albania',
				iso2: 'AL',
				iso3: 'ALB',
				locale: 'sq-AL',
				phoneCode: '+355',
			},
			{
				name: 'Algeria',
				iso2: 'DZ',
				iso3: 'DZA',
				locale: 'ar-DZ',
				phoneCode: '+213',
			},
			{
				name: 'Andorra',
				iso2: 'AD',
				iso3: 'AND',
				locale: 'ca-AD',
				phoneCode: '+376',
			},
			{
				name: 'Angola',
				iso2: 'AO',
				iso3: 'AGO',
				locale: 'pt-AO',
				phoneCode: '+244',
			},
			{
				name: 'Antigua and Barbuda',
				iso2: 'AG',
				iso3: 'ATG',
				locale: 'en-AG',
				phoneCode: '+1-268',
			},
			{
				name: 'Argentina',
				iso2: 'AR',
				iso3: 'ARG',
				locale: 'es-AR',
				phoneCode: '+54',
			},
			{
				name: 'Armenia',
				iso2: 'AM',
				iso3: 'ARM',
				locale: 'hy-AM',
				phoneCode: '+374',
			},
			{
				name: 'Australia',
				iso2: 'AU',
				iso3: 'AUS',
				locale: 'en-AU',
				phoneCode: '+61',
			},
			{
				name: 'Austria',
				iso2: 'AT',
				iso3: 'AUT',
				locale: 'de-AT',
				phoneCode: '+43',
			},
			{
				name: 'Azerbaijan',
				iso2: 'AZ',
				iso3: 'AZE',
				locale: 'az-AZ',
				phoneCode: '+994',
			},
			{
				name: 'Bahamas',
				iso2: 'BS',
				iso3: 'BHS',
				locale: 'en-BS',
				phoneCode: '+1-242',
			},
			{
				name: 'Bahrain',
				iso2: 'BH',
				iso3: 'BHR',
				locale: 'ar-BH',
				phoneCode: '+973',
			},
			{
				name: 'Bangladesh',
				iso2: 'BD',
				iso3: 'BGD',
				locale: 'bn-BD',
				phoneCode: '+880',
			},
			{
				name: 'Barbados',
				iso2: 'BB',
				iso3: 'BRB',
				locale: 'en-BB',
				phoneCode: '+1-246',
			},
			{
				name: 'Belarus',
				iso2: 'BY',
				iso3: 'BLR',
				locale: 'be-BY',
				phoneCode: '+375',
			},
			{
				name: 'Belgium',
				iso2: 'BE',
				iso3: 'BEL',
				locale: 'nl-BE',
				phoneCode: '+32',
			},
			{
				name: 'Belize',
				iso2: 'BZ',
				iso3: 'BLZ',
				locale: 'en-BZ',
				phoneCode: '+501',
			},
			{
				name: 'Benin',
				iso2: 'BJ',
				iso3: 'BEN',
				locale: 'fr-BJ',
				phoneCode: '+229',
			},
			{
				name: 'Bhutan',
				iso2: 'BT',
				iso3: 'BTN',
				locale: 'dz-BT',
				phoneCode: '+975',
			},
			{
				name: 'Bolivia',
				iso2: 'BO',
				iso3: 'BOL',
				locale: 'es-BO',
				phoneCode: '+591',
			},
			{
				name: 'Bosnia and Herzegovina',
				iso2: 'BA',
				iso3: 'BIH',
				locale: 'bs-BA',
				phoneCode: '+387',
			},
			{
				name: 'Botswana',
				iso2: 'BW',
				iso3: 'BWA',
				locale: 'en-BW',
				phoneCode: '+267',
			},
			{
				name: 'Brazil',
				iso2: 'BR',
				iso3: 'BRA',
				locale: 'pt-BR',
				phoneCode: '+55',
			},
			{
				name: 'Brunei',
				iso2: 'BN',
				iso3: 'BRN',
				locale: 'ms-BN',
				phoneCode: '+673',
			},
			{
				name: 'Bulgaria',
				iso2: 'BG',
				iso3: 'BGR',
				locale: 'bg-BG',
				phoneCode: '+359',
			},
			{
				name: 'Burkina Faso',
				iso2: 'BF',
				iso3: 'BFA',
				locale: 'fr-BF',
				phoneCode: '+226',
			},
			{
				name: 'Burundi',
				iso2: 'BI',
				iso3: 'BDI',
				locale: 'fr-BI',
				phoneCode: '+257',
			},
			{
				name: 'Cabo Verde',
				iso2: 'CV',
				iso3: 'CPV',
				locale: 'pt-CV',
				phoneCode: '+238',
			},
			{
				name: 'Cambodia',
				iso2: 'KH',
				iso3: 'KHM',
				locale: 'km-KH',
				phoneCode: '+855',
			},
			{
				name: 'Cameroon',
				iso2: 'CM',
				iso3: 'CMR',
				locale: 'fr-CM',
				phoneCode: '+237',
			},
			{
				name: 'Canada',
				iso2: 'CA',
				iso3: 'CAN',
				locale: 'en-CA',
				phoneCode: '+1',
			},
			{
				name: 'Central African Republic',
				iso2: 'CF',
				iso3: 'CAF',
				locale: 'fr-CF',
				phoneCode: '+236',
			},
			{
				name: 'Chad',
				iso2: 'TD',
				iso3: 'TCD',
				locale: 'fr-TD',
				phoneCode: '+235',
			},
			{
				name: 'Chile',
				iso2: 'CL',
				iso3: 'CHL',
				locale: 'es-CL',
				phoneCode: '+56',
			},
			{
				name: 'China',
				iso2: 'CN',
				iso3: 'CHN',
				locale: 'zh-CN',
				phoneCode: '+86',
			},
			{
				name: 'Colombia',
				iso2: 'CO',
				iso3: 'COL',
				locale: 'es-CO',
				phoneCode: '+57',
			},
			{
				name: 'Comoros',
				iso2: 'KM',
				iso3: 'COM',
				locale: 'ar-KM',
				phoneCode: '+269',
			},
			{
				name: 'Congo (Congo-Brazzaville)',
				iso2: 'CG',
				iso3: 'COG',
				locale: 'fr-CG',
				phoneCode: '+242',
			},
			{
				name: 'Congo (DRC)',
				iso2: 'CD',
				iso3: 'COD',
				locale: 'fr-CD',
				phoneCode: '+243',
			},
			{
				name: 'Costa Rica',
				iso2: 'CR',
				iso3: 'CRI',
				locale: 'es-CR',
				phoneCode: '+506',
			},
			{
				name: 'Croatia',
				iso2: 'HR',
				iso3: 'HRV',
				locale: 'hr-HR',
				phoneCode: '+385',
			},
			{
				name: 'Cuba',
				iso2: 'CU',
				iso3: 'CUB',
				locale: 'es-CU',
				phoneCode: '+53',
			},
			{
				name: 'Cyprus',
				iso2: 'CY',
				iso3: 'CYP',
				locale: 'el-CY',
				phoneCode: '+357',
			},
			{
				name: 'Czech Republic',
				iso2: 'CZ',
				iso3: 'CZE',
				locale: 'cs-CZ',
				phoneCode: '+420',
			},
			{
				name: 'Denmark',
				iso2: 'DK',
				iso3: 'DNK',
				locale: 'da-DK',
				phoneCode: '+45',
			},
			{
				name: 'Djibouti',
				iso2: 'DJ',
				iso3: 'DJI',
				locale: 'fr-DJ',
				phoneCode: '+253',
			},
			{
				name: 'Dominica',
				iso2: 'DM',
				iso3: 'DMA',
				locale: 'en-DM',
				phoneCode: '+1-767',
			},
			{
				name: 'Dominican Republic',
				iso2: 'DO',
				iso3: 'DOM',
				locale: 'es-DO',
				phoneCode: '+1-809',
			},
			{
				name: 'Ecuador',
				iso2: 'EC',
				iso3: 'ECU',
				locale: 'es-EC',
				phoneCode: '+593',
			},
			{
				name: 'Egypt',
				iso2: 'EG',
				iso3: 'EGY',
				locale: 'ar-EG',
				phoneCode: '+20',
			},
			{
				name: 'El Salvador',
				iso2: 'SV',
				iso3: 'SLV',
				locale: 'es-SV',
				phoneCode: '+503',
			},
			{
				name: 'Equatorial Guinea',
				iso2: 'GQ',
				iso3: 'GNQ',
				locale: 'es-GQ',
				phoneCode: '+240',
			},
			{
				name: 'Eritrea',
				iso2: 'ER',
				iso3: 'ERI',
				locale: 'ti-ER',
				phoneCode: '+291',
			},
			{
				name: 'Estonia',
				iso2: 'EE',
				iso3: 'EST',
				locale: 'et-EE',
				phoneCode: '+372',
			},
			{
				name: 'Eswatini',
				iso2: 'SZ',
				iso3: 'SWZ',
				locale: 'en-SZ',
				phoneCode: '+268',
			},
			{
				name: 'Ethiopia',
				iso2: 'ET',
				iso3: 'ETH',
				locale: 'am-ET',
				phoneCode: '+251',
			},
			{
				name: 'Fiji',
				iso2: 'FJ',
				iso3: 'FJI',
				locale: 'en-FJ',
				phoneCode: '+679',
			},
			{
				name: 'Finland',
				iso2: 'FI',
				iso3: 'FIN',
				locale: 'fi-FI',
				phoneCode: '+358',
			},
			{
				name: 'France',
				iso2: 'FR',
				iso3: 'FRA',
				locale: 'fr-FR',
				phoneCode: '+33',
			},
			{
				name: 'Gabon',
				iso2: 'GA',
				iso3: 'GAB',
				locale: 'fr-GA',
				phoneCode: '+241',
			},
			{
				name: 'Gambia',
				iso2: 'GM',
				iso3: 'GMB',
				locale: 'en-GM',
				phoneCode: '+220',
			},
			{
				name: 'Georgia',
				iso2: 'GE',
				iso3: 'GEO',
				locale: 'ka-GE',
				phoneCode: '+995',
			},
			{
				name: 'Germany',
				iso2: 'DE',
				iso3: 'DEU',
				locale: 'de-DE',
				phoneCode: '+49',
			},
			{
				name: 'Ghana',
				iso2: 'GH',
				iso3: 'GHA',
				locale: 'en-GH',
				phoneCode: '+233',
			},
			{
				name: 'Greece',
				iso2: 'GR',
				iso3: 'GRC',
				locale: 'el-GR',
				phoneCode: '+30',
			},
			{
				name: 'Grenada',
				iso2: 'GD',
				iso3: 'GRD',
				locale: 'en-GD',
				phoneCode: '+1-473',
			},
			{
				name: 'Guatemala',
				iso2: 'GT',
				iso3: 'GTM',
				locale: 'es-GT',
				phoneCode: '+502',
			},
			{
				name: 'Guinea',
				iso2: 'GN',
				iso3: 'GIN',
				locale: 'fr-GN',
				phoneCode: '+224',
			},
			{
				name: 'Guinea-Bissau',
				iso2: 'GW',
				iso3: 'GNB',
				locale: 'pt-GW',
				phoneCode: '+245',
			},
			{
				name: 'Guyana',
				iso2: 'GY',
				iso3: 'GUY',
				locale: 'en-GY',
				phoneCode: '+592',
			},
			{
				name: 'Haiti',
				iso2: 'HT',
				iso3: 'HTI',
				locale: 'fr-HT',
				phoneCode: '+509',
			},
			{
				name: 'Honduras',
				iso2: 'HN',
				iso3: 'HND',
				locale: 'es-HN',
				phoneCode: '+504',
			},
			{
				name: 'Hungary',
				iso2: 'HU',
				iso3: 'HUN',
				locale: 'hu-HU',
				phoneCode: '+36',
			},
			{
				name: 'Iceland',
				iso2: 'IS',
				iso3: 'ISL',
				locale: 'is-IS',
				phoneCode: '+354',
			},
			{
				name: 'India',
				iso2: 'IN',
				iso3: 'IND',
				locale: 'hi-IN',
				phoneCode: '+91',
			},
			{
				name: 'Indonesia',
				iso2: 'ID',
				iso3: 'IDN',
				locale: 'id-ID',
				phoneCode: '+62',
			},
			{
				name: 'Iran',
				iso2: 'IR',
				iso3: 'IRN',
				locale: 'fa-IR',
				phoneCode: '+98',
			},
			{
				name: 'Iraq',
				iso2: 'IQ',
				iso3: 'IRQ',
				locale: 'ar-IQ',
				phoneCode: '+964',
			},
			{
				name: 'Ireland',
				iso2: 'IE',
				iso3: 'IRL',
				locale: 'en-IE',
				phoneCode: '+353',
			},
			{
				name: 'Israel',
				iso2: 'IL',
				iso3: 'ISR',
				locale: 'he-IL',
				phoneCode: '+972',
			},
			{
				name: 'Italy',
				iso2: 'IT',
				iso3: 'ITA',
				locale: 'it-IT',
				phoneCode: '+39',
			},
			{
				name: 'Jamaica',
				iso2: 'JM',
				iso3: 'JAM',
				locale: 'en-JM',
				phoneCode: '+1-876',
			},
			{
				name: 'Japan',
				iso2: 'JP',
				iso3: 'JPN',
				locale: 'ja-JP',
				phoneCode: '+81',
			},
			{
				name: 'Jordan',
				iso2: 'JO',
				iso3: 'JOR',
				locale: 'ar-JO',
				phoneCode: '+962',
			},
			{
				name: 'Kazakhstan',
				iso2: 'KZ',
				iso3: 'KAZ',
				locale: 'kk-KZ',
				phoneCode: '+7',
			},
			{
				name: 'Kenya',
				iso2: 'KE',
				iso3: 'KEN',
				locale: 'sw-KE',
				phoneCode: '+254',
			},
			{
				name: 'Kiribati',
				iso2: 'KI',
				iso3: 'KIR',
				locale: 'en-KI',
				phoneCode: '+686',
			},
			{
				name: 'Kuwait',
				iso2: 'KW',
				iso3: 'KWT',
				locale: 'ar-KW',
				phoneCode: '+965',
			},
			{
				name: 'Kyrgyzstan',
				iso2: 'KG',
				iso3: 'KGZ',
				locale: 'ky-KG',
				phoneCode: '+996',
			},
			{
				name: 'Laos',
				iso2: 'LA',
				iso3: 'LAO',
				locale: 'lo-LA',
				phoneCode: '+856',
			},
			{
				name: 'Latvia',
				iso2: 'LV',
				iso3: 'LVA',
				locale: 'lv-LV',
				phoneCode: '+371',
			},
			{
				name: 'Lebanon',
				iso2: 'LB',
				iso3: 'LBN',
				locale: 'ar-LB',
				phoneCode: '+961',
			},
			{
				name: 'Lesotho',
				iso2: 'LS',
				iso3: 'LSO',
				locale: 'en-LS',
				phoneCode: '+266',
			},
			{
				name: 'Liberia',
				iso2: 'LR',
				iso3: 'LBR',
				locale: 'en-LR',
				phoneCode: '+231',
			},
			{
				name: 'Libya',
				iso2: 'LY',
				iso3: 'LBY',
				locale: 'ar-LY',
				phoneCode: '+218',
			},
			{
				name: 'Liechtenstein',
				iso2: 'LI',
				iso3: 'LIE',
				locale: 'de-LI',
				phoneCode: '+423',
			},
			{
				name: 'Lithuania',
				iso2: 'LT',
				iso3: 'LTU',
				locale: 'lt-LT',
				phoneCode: '+370',
			},
			{
				name: 'Luxembourg',
				iso2: 'LU',
				iso3: 'LUX',
				locale: 'fr-LU',
				phoneCode: '+352',
			},
			{
				name: 'Madagascar',
				iso2: 'MG',
				iso3: 'MDG',
				locale: 'mg-MG',
				phoneCode: '+261',
			},
			{
				name: 'Malawi',
				iso2: 'MW',
				iso3: 'MWI',
				locale: 'en-MW',
				phoneCode: '+265',
			},
			{
				name: 'Malaysia',
				iso2: 'MY',
				iso3: 'MYS',
				locale: 'ms-MY',
				phoneCode: '+60',
			},
			{
				name: 'Maldives',
				iso2: 'MV',
				iso3: 'MDV',
				locale: 'dv-MV',
				phoneCode: '+960',
			},
			{
				name: 'Mali',
				iso2: 'ML',
				iso3: 'MLI',
				locale: 'fr-ML',
				phoneCode: '+223',
			},
			{
				name: 'Malta',
				iso2: 'MT',
				iso3: 'MLT',
				locale: 'mt-MT',
				phoneCode: '+356',
			},
			{
				name: 'Marshall Islands',
				iso2: 'MH',
				iso3: 'MHL',
				locale: 'en-MH',
				phoneCode: '+692',
			},
			{
				name: 'Mauritania',
				iso2: 'MR',
				iso3: 'MRT',
				locale: 'ar-MR',
				phoneCode: '+222',
			},
			{
				name: 'Mauritius',
				iso2: 'MU',
				iso3: 'MUS',
				locale: 'en-MU',
				phoneCode: '+230',
			},
			{
				name: 'Mexico',
				iso2: 'MX',
				iso3: 'MEX',
				locale: 'es-MX',
				phoneCode: '+52',
			},
			{
				name: 'Micronesia',
				iso2: 'FM',
				iso3: 'FSM',
				locale: 'en-FM',
				phoneCode: '+691',
			},
			{
				name: 'Moldova',
				iso2: 'MD',
				iso3: 'MDA',
				locale: 'ro-MD',
				phoneCode: '+373',
			},
			{
				name: 'Monaco',
				iso2: 'MC',
				iso3: 'MCO',
				locale: 'fr-MC',
				phoneCode: '+377',
			},
			{
				name: 'Mongolia',
				iso2: 'MN',
				iso3: 'MNG',
				locale: 'mn-MN',
				phoneCode: '+976',
			},
			{
				name: 'Montenegro',
				iso2: 'ME',
				iso3: 'MNE',
				locale: 'sr-ME',
				phoneCode: '+382',
			},
			{
				name: 'Morocco',
				iso2: 'MA',
				iso3: 'MAR',
				locale: 'ar-MA',
				phoneCode: '+212',
			},
			{
				name: 'Mozambique',
				iso2: 'MZ',
				iso3: 'MOZ',
				locale: 'pt-MZ',
				phoneCode: '+258',
			},
			{
				name: 'Myanmar',
				iso2: 'MM',
				iso3: 'MMR',
				locale: 'my-MM',
				phoneCode: '+95',
			},
			{
				name: 'Namibia',
				iso2: 'NA',
				iso3: 'NAM',
				locale: 'en-NA',
				phoneCode: '+264',
			},
			{
				name: 'Nauru',
				iso2: 'NR',
				iso3: 'NRU',
				locale: 'en-NR',
				phoneCode: '+674',
			},
			{
				name: 'Nepal',
				iso2: 'NP',
				iso3: 'NPL',
				locale: 'ne-NP',
				phoneCode: '+977',
			},
			{
				name: 'Netherlands',
				iso2: 'NL',
				iso3: 'NLD',
				locale: 'nl-NL',
				phoneCode: '+31',
			},
			{
				name: 'New Zealand',
				iso2: 'NZ',
				iso3: 'NZL',
				locale: 'en-NZ',
				phoneCode: '+64',
			},
			{
				name: 'Nicaragua',
				iso2: 'NI',
				iso3: 'NIC',
				locale: 'es-NI',
				phoneCode: '+505',
			},
			{
				name: 'Niger',
				iso2: 'NE',
				iso3: 'NER',
				locale: 'fr-NE',
				phoneCode: '+227',
			},
			{
				name: 'Nigeria',
				iso2: 'NG',
				iso3: 'NGA',
				locale: 'en-NG',
				phoneCode: '+234',
			},
			{
				name: 'North Korea',
				iso2: 'KP',
				iso3: 'PRK',
				locale: 'ko-KP',
				phoneCode: '+850',
			},
			{
				name: 'North Macedonia',
				iso2: 'MK',
				iso3: 'MKD',
				locale: 'mk-MK',
				phoneCode: '+389',
			},
			{
				name: 'Norway',
				iso2: 'NO',
				iso3: 'NOR',
				locale: 'nb-NO',
				phoneCode: '+47',
			},
			{
				name: 'Oman',
				iso2: 'OM',
				iso3: 'OMN',
				locale: 'ar-OM',
				phoneCode: '+968',
			},
			{
				name: 'Pakistan',
				iso2: 'PK',
				iso3: 'PAK',
				locale: 'ur-PK',
				phoneCode: '+92',
			},
			{
				name: 'Palau',
				iso2: 'PW',
				iso3: 'PLW',
				locale: 'en-PW',
				phoneCode: '+680',
			},
			{
				name: 'Palestine',
				iso2: 'PS',
				iso3: 'PSE',
				locale: 'ar-PS',
				phoneCode: '+970',
			},
			{
				name: 'Panama',
				iso2: 'PA',
				iso3: 'PAN',
				locale: 'es-PA',
				phoneCode: '+507',
			},
			{
				name: 'Papua New Guinea',
				iso2: 'PG',
				iso3: 'PNG',
				locale: 'en-PG',
				phoneCode: '+675',
			},
			{
				name: 'Paraguay',
				iso2: 'PY',
				iso3: 'PRY',
				locale: 'es-PY',
				phoneCode: '+595',
			},
			{
				name: 'Peru',
				iso2: 'PE',
				iso3: 'PER',
				locale: 'es-PE',
				phoneCode: '+51',
			},
			{
				name: 'Philippines',
				iso2: 'PH',
				iso3: 'PHL',
				locale: 'en-PH',
				phoneCode: '+63',
			},
			{
				name: 'Poland',
				iso2: 'PL',
				iso3: 'POL',
				locale: 'pl-PL',
				phoneCode: '+48',
			},
			{
				name: 'Portugal',
				iso2: 'PT',
				iso3: 'PRT',
				locale: 'pt-PT',
				phoneCode: '+351',
			},
			{
				name: 'Qatar',
				iso2: 'QA',
				iso3: 'QAT',
				locale: 'ar-QA',
				phoneCode: '+974',
			},
			{
				name: 'Romania',
				iso2: 'RO',
				iso3: 'ROU',
				locale: 'ro-RO',
				phoneCode: '+40',
			},
			{
				name: 'Russia',
				iso2: 'RU',
				iso3: 'RUS',
				locale: 'ru-RU',
				phoneCode: '+7',
			},
			{
				name: 'Rwanda',
				iso2: 'RW',
				iso3: 'RWA',
				locale: 'rw-RW',
				phoneCode: '+250',
			},
			{
				name: 'Saint Kitts and Nevis',
				iso2: 'KN',
				iso3: 'KNA',
				locale: 'en-KN',
				phoneCode: '+1-869',
			},
			{
				name: 'Saint Lucia',
				iso2: 'LC',
				iso3: 'LCA',
				locale: 'en-LC',
				phoneCode: '+1-758',
			},
			{
				name: 'Saint Vincent and the Grenadines',
				iso2: 'VC',
				iso3: 'VCT',
				locale: 'en-VC',
				phoneCode: '+1-784',
			},
			{
				name: 'Samoa',
				iso2: 'WS',
				iso3: 'WSM',
				locale: 'sm-WS',
				phoneCode: '+685',
			},
			{
				name: 'San Marino',
				iso2: 'SM',
				iso3: 'SMR',
				locale: 'it-SM',
				phoneCode: '+378',
			},
			{
				name: 'Sao Tome and Principe',
				iso2: 'ST',
				iso3: 'STP',
				locale: 'pt-ST',
				phoneCode: '+239',
			},
			{
				name: 'Saudi Arabia',
				iso2: 'SA',
				iso3: 'SAU',
				locale: 'ar-SA',
				phoneCode: '+966',
			},
			{
				name: 'Senegal',
				iso2: 'SN',
				iso3: 'SEN',
				locale: 'fr-SN',
				phoneCode: '+221',
			},
			{
				name: 'Serbia',
				iso2: 'RS',
				iso3: 'SRB',
				locale: 'sr-RS',
				phoneCode: '+381',
			},
			{
				name: 'Seychelles',
				iso2: 'SC',
				iso3: 'SYC',
				locale: 'en-SC',
				phoneCode: '+248',
			},
			{
				name: 'Sierra Leone',
				iso2: 'SL',
				iso3: 'SLE',
				locale: 'en-SL',
				phoneCode: '+232',
			},
			{
				name: 'Singapore',
				iso2: 'SG',
				iso3: 'SGP',
				locale: 'en-SG',
				phoneCode: '+65',
			},
			{
				name: 'Slovakia',
				iso2: 'SK',
				iso3: 'SVK',
				locale: 'sk-SK',
				phoneCode: '+421',
			},
			{
				name: 'Slovenia',
				iso2: 'SI',
				iso3: 'SVN',
				locale: 'sl-SI',
				phoneCode: '+386',
			},
			{
				name: 'Solomon Islands',
				iso2: 'SB',
				iso3: 'SLB',
				locale: 'en-SB',
				phoneCode: '+677',
			},
			{
				name: 'Somalia',
				iso2: 'SO',
				iso3: 'SOM',
				locale: 'so-SO',
				phoneCode: '+252',
			},
			{
				name: 'South Africa',
				iso2: 'ZA',
				iso3: 'ZAF',
				locale: 'en-ZA',
				phoneCode: '+27',
			},
			{
				name: 'South Korea',
				iso2: 'KR',
				iso3: 'KOR',
				locale: 'ko-KR',
				phoneCode: '+82',
			},
			{
				name: 'South Sudan',
				iso2: 'SS',
				iso3: 'SSD',
				locale: 'en-SS',
				phoneCode: '+211',
			},
			{
				name: 'Spain',
				iso2: 'ES',
				iso3: 'ESP',
				locale: 'es-ES',
				phoneCode: '+34',
			},
			{
				name: 'Sri Lanka',
				iso2: 'LK',
				iso3: 'LKA',
				locale: 'si-LK',
				phoneCode: '+94',
			},
			{
				name: 'Sudan',
				iso2: 'SD',
				iso3: 'SDN',
				locale: 'ar-SD',
				phoneCode: '+249',
			},
			{
				name: 'Suriname',
				iso2: 'SR',
				iso3: 'SUR',
				locale: 'nl-SR',
				phoneCode: '+597',
			},
			{
				name: 'Sweden',
				iso2: 'SE',
				iso3: 'SWE',
				locale: 'sv-SE',
				phoneCode: '+46',
			},
			{
				name: 'Switzerland',
				iso2: 'CH',
				iso3: 'CHE',
				locale: 'de-CH',
				phoneCode: '+41',
			},
			{
				name: 'Syria',
				iso2: 'SY',
				iso3: 'SYR',
				locale: 'ar-SY',
				phoneCode: '+963',
			},
			{
				name: 'Taiwan',
				iso2: 'TW',
				iso3: 'TWN',
				locale: 'zh-TW',
				phoneCode: '+886',
			},
			{
				name: 'Tajikistan',
				iso2: 'TJ',
				iso3: 'TJK',
				locale: 'tg-TJ',
				phoneCode: '+992',
			},
			{
				name: 'Tanzania',
				iso2: 'TZ',
				iso3: 'TZA',
				locale: 'sw-TZ',
				phoneCode: '+255',
			},
			{
				name: 'Thailand',
				iso2: 'TH',
				iso3: 'THA',
				locale: 'th-TH',
				phoneCode: '+66',
			},
			{
				name: 'Timor-Leste',
				iso2: 'TL',
				iso3: 'TLS',
				locale: 'pt-TL',
				phoneCode: '+670',
			},
			{
				name: 'Togo',
				iso2: 'TG',
				iso3: 'TGO',
				locale: 'fr-TG',
				phoneCode: '+228',
			},
			{
				name: 'Tonga',
				iso2: 'TO',
				iso3: 'TON',
				locale: 'to-TO',
				phoneCode: '+676',
			},
			{
				name: 'Trinidad and Tobago',
				iso2: 'TT',
				iso3: 'TTO',
				locale: 'en-TT',
				phoneCode: '+1-868',
			},
			{
				name: 'Tunisia',
				iso2: 'TN',
				iso3: 'TUN',
				locale: 'ar-TN',
				phoneCode: '+216',
			},
			{
				name: 'Turkey',
				iso2: 'TR',
				iso3: 'TUR',
				locale: 'tr-TR',
				phoneCode: '+90',
			},
			{
				name: 'Turkmenistan',
				iso2: 'TM',
				iso3: 'TKM',
				locale: 'tk-TM',
				phoneCode: '+993',
			},
			{
				name: 'Tuvalu',
				iso2: 'TV',
				iso3: 'TUV',
				locale: 'en-TV',
				phoneCode: '+688',
			},
			{
				name: 'Uganda',
				iso2: 'UG',
				iso3: 'UGA',
				locale: 'en-UG',
				phoneCode: '+256',
			},
			{
				name: 'Ukraine',
				iso2: 'UA',
				iso3: 'UKR',
				locale: 'uk-UA',
				phoneCode: '+380',
			},
			{
				name: 'United Arab Emirates',
				iso2: 'AE',
				iso3: 'ARE',
				locale: 'ar-AE',
				phoneCode: '+971',
			},
			{
				name: 'United Kingdom',
				iso2: 'GB',
				iso3: 'GBR',
				locale: 'en-GB',
				phoneCode: '+44',
			},
			{
				name: 'United States',
				iso2: 'US',
				iso3: 'USA',
				locale: 'en-US',
				phoneCode: '+1',
			},
			{
				name: 'Uruguay',
				iso2: 'UY',
				iso3: 'URY',
				locale: 'es-UY',
				phoneCode: '+598',
			},
			{
				name: 'Uzbekistan',
				iso2: 'UZ',
				iso3: 'UZB',
				locale: 'uz-UZ',
				phoneCode: '+998',
			},
			{
				name: 'Vanuatu',
				iso2: 'VU',
				iso3: 'VUT',
				locale: 'bi-VU',
				phoneCode: '+678',
			},
			{
				name: 'Vatican City',
				iso2: 'VA',
				iso3: 'VAT',
				locale: 'it-VA',
				phoneCode: '+379',
			},
			{
				name: 'Venezuela',
				iso2: 'VE',
				iso3: 'VEN',
				locale: 'es-VE',
				phoneCode: '+58',
			},
			{
				name: 'Vietnam',
				iso2: 'VN',
				iso3: 'VNM',
				locale: 'vi-VN',
				phoneCode: '+84',
			},
			{
				name: 'Yemen',
				iso2: 'YE',
				iso3: 'YEM',
				locale: 'ar-YE',
				phoneCode: '+967',
			},
			{
				name: 'Zambia',
				iso2: 'ZM',
				iso3: 'ZMB',
				locale: 'en-ZM',
				phoneCode: '+260',
			},
			{
				name: 'Zimbabwe',
				iso2: 'ZW',
				iso3: 'ZWE',
				locale: 'en-ZW',
				phoneCode: '+263',
			},
		],
	})
}
